name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version (and git tag)"
        required: true

run-name: "Release ${{ inputs.version }}"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [ 17 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk-version }}

      - name: Release
        uses: joffrey-bion/gradle-library-release-action@v2
        with:
          version: ${{ inputs.version }}
          gpg-signing-key: ${{ secrets.GPG_SECRET_ASCII_ARMORED }}
          gpg-signing-password: ${{ secrets.GPG_PASSWORD }}
          sonatype-username: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          sonatype-password: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
          gradle-publish-tasks: publishToSonatype closeAndReleaseSonatypeStagingRepository
